content_gallery_testapp/testapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'testapp'

urlpatterns = [
    url(
        r'^cat/$',
        views.CatListView.as_view(),
        name='cat_list'
    ),
    url(
        r'^cat/(?P<pk>\d+)/$',
        views.CatDetailView.as_view(),
        name='cat_detail'
    ),
]

content_gallery_testapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # set the root URL for the Content Gallery app
    url(r'^gallery/', include('content_gallery.urls')),
    url(r'^testapp/', include('testapp.urls')),
    url(r'^$', RedirectView.as_view(pattern_name="testapp:cat_list")),
]

# serve images from MEDIA_ROOT directory in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content_gallery_testapp/testapp/models.py
from django.db import models

from content_gallery.models import ContentGalleryMixin

# the ContentGalleryMixin enables the Content Gallery for the model

class Cat(ContentGalleryMixin, models.Model):

    SEX_CHOICES = {
        ('M', "Male"),
        ('F', "Female")
    }

    name = models.CharField(max_length=50)
    age = models.IntegerField(null=True, blank=True)
    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
        null=True,
        blank=True
    )
    about = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

content_gallery_testapp/testapp/views.py
from django.views import generic

from . import models

class CatListView(generic.ListView):
    model = models.Cat
    template_name = 'testapp/cat_list.html'
    context_object_name = 'cats'


class CatDetailView(generic.DetailView):
    model = models.Cat
    template_name = 'testapp/cat_detail.html'
    context_object_name = 'cat'

content_gallery_testapp/testapp/templates/testapp/cat_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>The django-content-gallery test application</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='StyleSheet' type='text/css'>
  <link href="{% static 'css/base.css' %}" type="text/css" rel="StyleSheet">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="{% static 'js/base.js' %}"></script>
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
</head>
<body>
{% include "content_gallery/_image_view.html" %}
<div class="header">
  <h1>The django-content-gallery test application</h1>
</div>
<div class="cat-content">
{% block content %}
{% endblock content %}
</div>
<div class="footer">
  <div class="logos">
    <a href="https://python.org"><img src="{% static 'img/python.png' %}"></a>
    <a href="https://djangoproject.com"><img src="{% static 'img/django.png' %}"></a>
    <a href="https://github.com"><img src="{% static 'img/github.png' %}"></a>
  </div>
  <p>The <a href="https://github.com/Kemaweyan/django-content-gallery">django-content-gallery</a>
  project &copy; 2017</p>
</div>
</body>
</html>

content_gallery_testapp/testapp/templates/testapp/cat_detail.html
{% extends "testapp/cat_base.html" %}
{% load static content_gallery %}
{% block content %}
<div class="cat-photo">
  {% gallery_preview cat %}
</div>
<div class="cat-description">
  <h2>{{ cat.name }}</h2>
  {% if cat.about %}
    <p>{{ cat.about }}</p>
  {% else %}
    <p class="no-description">no description</p>
  {% endif %}
  <p>This page demonstrates a preview widget of the django-content-gallery
  application. The widget displays a preview of the first image related to
  the object or the no-image icon if there are not images. Click on the
  preview opens the gallery with all related to the object images. The
  preview widget is meant for using mainly on detail views.</p>
</div>
<div class="cleaner"></div>
<div class="back-link">
  &#8227; <a href="..">Back to the list</a>
</div>
{% endblock content %}

content_gallery_testapp/testapp/templates/testapp/cat_list.html
{% extends "testapp/cat_base.html" %}
{% load static content_gallery %}
{% block content %}

<p>This is a test application that demonstrates how to integrate the
django-content-gallery into a project. The application contains two views:
a list view containing a list of cats and a detail view with detailed information
of a cat. The database contains two cats: the one named Semargl with a collection
of photos to demonstrate features of the content gallery, and some unknown cat
that has not photos to demontrate an empty gallery.</p>

<p>This page demonstrates a small preview widget of the django-content-gallery
application. The widget displays a small preview of the first image related to
the object or the small no-image icon if there are not images. Click on the
preview opens the gallery with all related to the object images. The small 
preview widget is meant for using mainly on list views.</p>

<div class="footprint"></div>

<table class="cats-table">
  <tbody>
    {% for cat in cats %}
      <tr>
        <td class="table-photo">
          {% gallery_small_preview cat %}
        </td>
        <td class="table-description">
          <h3><a href="{{ cat.pk }}">{{ cat.name }}</a></h3>
          {% if cat.age or cat.sex %}
            <p>
            {% if cat.age %}
              {{ cat.age }} year{{ cat.age|pluralize }} old
            {% endif %}
            {% if cat.sex %}
              {% if cat.age %},{% endif %}
              {{ cat.get_sex_display|lower }}
            {% endif %}
            </p>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}